### ISSUE TITLE
Messaging: Cannot create multiple messengers in the same context anymore

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/webext-core#24]
### Overview

I noticed this while working on #21 while updating the demo extension. You should be able to do this:

```ts
const messenger1 = defineExtensionMessaging();
const messenger2 = defineExtensionMessaging();
```

Messages sent to and from `messenger1` should not trigger listeners for `messenger2`, and vice-versa.

Why is this important? Because each `@webext-core/proxy-service` sets up it's own listeners internally which should not effect any other proxy services or other messenger definitions.

### Reproduction

Run the `packages/messaging-demo` extension, and press any of the buttons on the popup.

### Todo

- [x] ~~_Locate the regression_~~ https://github.com/aklinker1/webext-core/commit/8c536db4f5dbb8232b92516d5065855639eb9bf6#diff-4e590c2a32420547792e5d50f072fdd36ab78cade1ba59ea629c1ac44075a04cR87-R89
- [x] ~~_Fix it_~~ 71c654da9a0fde64f9ce7eb59bea650632a1fa0d
- [x] ~~_Add tests so this doesn't happen again_~~ 71c654da9a0fde64f9ce7eb59bea650632a1fa0d

**Comment by aklinker1** [comment]
Closed by https://github.com/aklinker1/webext-core/commit/71c654da9a0fde64f9ce7eb59bea650632a1fa0d
